#!/bin/bash
#
#  Copyright (c) 2021, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#   Description:
#       This script manipulates accept_ra* configurations.
#
#   Environments:
#   - INFRA_IF_NAME: The infrastruture interface name on which the otbr-agent will
#                    will be running. This is usually "wlan0" for WiFi link and
#                    "eth0" for Ethernet link. "wlan0" will be used if not specified.
#

INFRA_IF_NAME="${INFRA_IF_NAME:-wlan0}"

readonly SYSCTL_ACCEPT_RA=/etc/sysctl.d/60-otbr-accept-ra.conf

accept_ra_install()
{
    sudo tee $SYSCTL_ACCEPT_RA <<EOF
net.ipv6.conf.${INFRA_IF_NAME}.accept_ra = 2
net.ipv6.conf.${INFRA_IF_NAME}.accept_ra_rt_info_max_plen = 64
EOF
}

accept_ra_uninstall()
{
    test ! -f $SYSCTL_ACCEPT_RA || sudo rm -v $SYSCTL_ACCEPT_RA
}

accept_ra_enable()
{
    echo 2 | sudo tee /proc/sys/net/ipv6/conf/${INFRA_IF_NAME}/accept_ra || die 'Failed to enable IPv6 RA!'
    echo 64 | sudo tee /proc/sys/net/ipv6/conf/${INFRA_IF_NAME}/accept_ra_rt_info_max_plen || die 'Failed to enable IPv6 RIO!'
}
